# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for Rad-Crawls
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Rad-Crawls' do
pod 'Alamofire', '~> 4.5'
end
